
version: '3'

services: 
  api-rest:
    image: bitnami/postgresql
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api-rest